version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  networks:
    - main
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/api/prom/push"

services:
  prometheus:
    <<: *defaults
    image: prom/prometheus:latest
    volumes:
      - prometheus_vol:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    <<: *defaults
    image: 'grafana/grafana:latest'
    env_file:
      - ./grafana/.env
    volumes:
      - grafana_vol:/var/lib/grafana

  loki:
    <<: *defaults
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "127.0.0.1:3100:3100"

networks:
  main:
    external: true

volumes:
  grafana_vol:
  prometheus_vol:
  