version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  networks:
    - main
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/api/prom/push"

services:
  prometheus:
    <<: *defaults
    build: ./prometheus
    volumes:
      - prometheus_vol:/prometheus

  grafana:
    <<: *defaults
    image: 'grafana/grafana:latest'
    env_file:
      - ./grafana/.env
    volumes:
      - grafana_vol:/var/lib/grafana

  loki:
    <<: *defaults
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100

networks:
  main:
    external: true

volumes:
  grafana_vol:
  prometheus_vol:
  