global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'server'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'bot'
    static_configs:
      - targets: ['bot:5000']

  - job_name: 'api'
    static_configs:
      - targets: ['api:4000']